apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: hoory-mailer
  namespace: kafka
spec:
  clusterRef:
    name: core
  name: hoory-mailer
  partitions: 3
  replicationFactor: 3
